name: Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run Tests
        env:
          MimirUptime_Headless__JwtIssuer: ${{ secrets.JwtIssuer }}
          MimirUptime_Headless__JwtSecretKey: ${{ secrets.JwtSecretKey }}
          MimirUptime_PagerDuty__Enabled: true
          MimirUptime_PagerDuty__RoutingKey: ${{ secrets.MimirRoutingKey }}

        run: |
          dotnet restore mimir-uptime.sln
          dotnet test mimir-uptime.sln
